# Generated by Django 6.0.2 on 2026-03-05 19:05
from django.db import migrations

def add_categories(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    categories = [
        {'name': 'Electronics', 'description': 'Electronic devices and gadgets', 'icon': 'bi-cpu'},
        {'name': 'Furniture', 'description': 'Household furniture items', 'icon': 'bi-chair'},
        {'name': 'Clothing', 'description': 'Clothes and fashion items', 'icon': 'bi-handbag'},
        {'name': 'Books', 'description': 'Books and educational materials', 'icon': 'bi-book'},
        {'name': 'Sports', 'description': 'Sports equipment and outdoor gear', 'icon': 'bi-basketball'},
        {'name': 'Kitchen', 'description': 'Kitchen appliances and utensils', 'icon': 'bi-cup-hot'},
        {'name': 'Tools', 'description': 'Tools and hardware', 'icon': 'bi-wrench'},
        {'name': 'Toys', 'description': 'Games and toys', 'icon': 'bi-joystick'},
    ]
    
    for category_data in categories:
        Category.objects.get_or_create(
            name=category_data['name'],
            defaults={
                'description': category_data['description'],
                'icon': category_data['icon']
            }
        )

def remove_categories(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    Category.objects.filter(name__in=[
        'Electronics', 'Furniture', 'Clothing', 'Books',
        'Sports', 'Kitchen', 'Tools', 'Toys'
    ]).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),  # Update this to match your last migration
    ]

    operations = [
        migrations.RunPython(add_categories, remove_categories),
    ]
