# Generated by Django 6.0.2 on 2026-03-24 08:55

from django.db import migrations

def geocode_location(location):
    """Geocode a location string to get latitude and longitude."""
    if not location:
        return None, None
    
    try:
        import requests
        # Using Nominatim API (OpenStreetMap) - free and no API key required
        url = f"https://nominatim.openstreetmap.org/search"
        params = {
            'q': location,
            'format': 'json',
            'limit': 1
        }
        headers = {
            'User-Agent': 'ShareLocal/1.0'
        }
        response = requests.get(url, params=params, headers=headers, timeout=5)
        response.raise_for_status()
        data = response.json()
        
        if data:
            return float(data[0]['lat']), float(data[0]['lon'])
    except Exception:
        # Gracefully handle any errors (including missing requests library)
        pass
    
    return None, None

def geocode_existing_profiles(apps, schema_editor):
    """Geocode existing user profiles that have location but no coordinates."""
    UserProfile = apps.get_model('accounts', 'UserProfile')
    
    for profile in UserProfile.objects.filter(location__isnull=False).exclude(latitude__isnull=False, longitude__isnull=False):
        lat, lon = geocode_location(profile.location)
        if lat is not None and lon is not None:
            profile.latitude = lat
            profile.longitude = lon
            profile.save(update_fields=['latitude', 'longitude'])

def reverse_geocode_profiles(apps, schema_editor):
    """Reverse geocoding - clear coordinates."""
    UserProfile = apps.get_model('accounts', 'UserProfile')
    UserProfile.objects.filter(latitude__isnull=False, longitude__isnull=False).update(latitude=None, longitude=None)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_latitude_and_more'),
    ]

    operations = [
        migrations.RunPython(geocode_existing_profiles, reverse_geocode_profiles),
    ]
