# Generated by Django 6.0.2 on 2026-03-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_latitude_item_longitude_alter_item_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, help_text='Location inherited from owner profile', max_length=100, null=True),
        ),
    ]
