# Generated by Django 6.0.2 on 2026-03-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_options_remove_item_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Item latitude for nearest search', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Item longitude for nearest search', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Share', 'Give Away'), ('Sell', 'Sell'), ('Rent', 'Rent')], default='Share', max_length=20),
        ),
    ]
