# Generated by Django 6.0.2 on 2026-03-24 08:03

from django.db import migrations

def geocode_location(location):
    """Geocode a location string to get latitude and longitude."""
    if not location:
        return None, None
    
    try:
        import requests
        # Using Nominatim API (OpenStreetMap) - free and no API key required
        url = f"https://nominatim.openstreetmap.org/search"
        params = {
            'q': location,
            'format': 'json',
            'limit': 1
        }
        headers = {
            'User-Agent': 'ShareLocal/1.0'
        }
        response = requests.get(url, params=params, headers=headers, timeout=5)
        response.raise_for_status()
        data = response.json()
        
        if data:
            return float(data[0]['lat']), float(data[0]['lon'])
    except Exception:
        # Gracefully handle any errors (including missing requests library)
        pass
    
    return None, None

def geocode_existing_items(apps, schema_editor):
    """Geocode existing items that have location but no coordinates."""
    Item = apps.get_model('items', 'Item')
    
    for item in Item.objects.filter(location__isnull=False).exclude(latitude__isnull=False, longitude__isnull=False):
        lat, lon = geocode_location(item.location)
        if lat is not None and lon is not None:
            item.latitude = lat
            item.longitude = lon
            item.save(update_fields=['latitude', 'longitude'])

def reverse_geocode(apps, schema_editor):
    """Reverse geocoding - clear coordinates."""
    Item = apps.get_model('items', 'Item')
    Item.objects.filter(latitude__isnull=False, longitude__isnull=False).update(latitude=None, longitude=None)

class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_backfill_item_locations'),
    ]

    operations = [
        migrations.RunPython(geocode_existing_items, reverse_geocode),
    ]
